Use new base image that uses supervisor, updated retry script

diff --git a/magento/scripts/retry b/magento/scripts/retry
--- a/magento/scripts/retry
+++ b/magento/scripts/retry
@@ -1,22 +1,21 @@
 #!/bin/bash
 
-# Set the maximum number of retries
-max_retries=5
+MAX_RETRIES=5
+COUNT=0
 
-# Set the initial number of retries to 0
-retries=0
+while true; do
+    eval "$1"
+    EXIT_CODE=$?
+    if [ $EXIT_CODE -eq 0 ]; then
+        exit 0
+    fi
 
-# Set the command to be executed as the first argument
-cmd=$1
+    COUNT=$((COUNT + 1))
+    if [ $COUNT -ge $MAX_RETRIES ]; then
+        echo "Command failed after $MAX_RETRIES attempts."
+        exit $EXIT_CODE
+    fi
 
-# Execute the command until it succeeds or the maximum number of retries is reached
-while ! eval $cmd 2>&1 | tee /dev/stderr && [ $retries -lt $max_retries ]; do
-  echo "Command failed. Retry attempt $retries"
-  retries=$((retries+1))
-  sleep 1
+    echo "Retry $COUNT/$MAX_RETRIES failed. Retrying..."
+    sleep 1
 done
-
-# If the maximum number of retries was reached, exit with a non-zero exit code
-if [ $retries -eq $max_retries ]; then
-  exit 1
-fi
